version: '3.1'

services:
  springboot:
    image: 383997292512.dkr.ecr.ap-south-1.amazonaws.com/general:tag
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=abhishek
    - MONGO_DB_PASSWORD=dev@123
    ports:
    - 8080:8080
    depends_on:
    - mongo
    networks:
    - network111



  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=abhishek
    - MONGO_INITDB_ROOT_PASSWORD=dev@123
    volumes:
    - mongovol:/data/db
    networks:
    - network111

volumes:
  mongovol:
 

networks:
  network111:
    external: true
