version: '3.1'

services:
  springboot:
    image: 383997292512.dkr.ecr.ap-south-1.amazonaws.com/general:tag
    restart: always
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
    - 8080:8080
    depends_on:
    - mongo
    networks:
    - network11



  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
    - mongovol:/data/db
    restart: always
    networks:
    - network11

volumes:
  mongovol:
    external: true

networks:
  network11:
    external: true
