version: '3.1'

services:
  springboot:
    image: 383997292512.dkr.ecr.ap-south-1.amazonaws.com/general:tag
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=abhishek
    - MONGO_DB_PASSWORD=dev@123
    ports:
    - 7000:8080
    depends_on:
    - mongo
    networks:
    - network111
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        delay: 10s
        condition: on-failure
        max_attempts: 4



  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=abhishek
    - MONGO_INITDB_ROOT_PASSWORD=dev@123
    volumes:
    - mongovol:/data/db
    networks:
    - network111
    deploy:
    replicas: 3

volumes:
  mongovol:
 

networks:
  network111:
    external: true
